### ISSUE TITLE
Can you build your magic uwp-rs app to ARM target?

### ISSUE THREAD

**Issue by mediaexplorer74** [bdbai/firstuwp-rs#2]
Hi.

I explored Tech. req. of your MS Store app. You noted that your app is Hololens/XBox/Mobile-compatible. Ok.. but I seen only x64 target:
![image](https://user-images.githubusercontent.com/12032735/234355898-761d72ca-b34a-46fc-a99b-87b270b9dd4c.png)
Of couse, Min. os. build 10240 is very cool :) I'm big fanboy of Microsoft Windows 10 Mobile (W10M at short) os. 
I have Lumia 640 DS winphone with experimental W10M os build 10270 (Project Astoria , for old Android's apk run).
So, can you build your magic uwp-rs app to ARM target? :)

Best,
MediaExplorer

**Comment by bdbai** [comment]
Hi @mediaexplorer74 , thanks for your interest in this toy project. It has been a long time since I've worked on this, so I couldn't really remember whether I've uploaded the ARM package to the store or not. Could you try to build the project by following the instructions mentioned in README? Things may have changed and please just let me know if there is any issues.

I will also attach an ARM app package that you can sideload into the device. The signature seems expired so you probably need to sign again. The `VCLibs` one is the dependency package that you may need.

[FirstUwp_0.0.1.0_arm_Test.zip](https://github.com/bdbai/firstuwp-rs/files/11325366/FirstUwp_0.0.1.0_arm_Test.zip)
[Microsoft.VCLibs.ARM.14.00.appx.zip](https://github.com/bdbai/firstuwp-rs/files/11325427/Microsoft.VCLibs.ARM.14.00.appx.zip)

**Comment by mediaexplorer74** [comment]
[bdbai](https://github.com/bdbai), thank you very mich. You're genius!
The expired signature is not big problem for fully unlocked phone, i think )
Ok, I'll try to sideload into the device.
About  README and "Rust magic":  I'm so silly at modern programming deals... And my 12-year old notebook has only last 4 GB freespace... it's no good )) So, the time that I can try to repeat your magic is so far... =)

--------------
Ready! 
The quick results:
Lumia 640DS: FirstUwp_0.0.1.0_arm_Test.appx package "installed" normally but app failed (halted) on run (XAML errors such CornerRadius.. 10240 sdk don't support that 'modern' property, IMHO))
Lumia 950: all seems to be ok for W10M build 15254! 
Congradulations, my issue/problem solved :)
Have a nice day, you are very cool developer/geek!!! I hope one day some crazy dev-man explored bdbai/firstuwp-rs repo andddddddddd... ports firefox (c++ plus rust as i know) to arm/uwp :)  
![image](https://user-images.githubusercontent.com/12032735/234375805-ab482036-247d-4afa-b8d5-906804efb0aa.png)
